site_url: https://ntn-boilerplate.netlify.app/
logo_url: https://ntn-boilerplate.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - label: 'Steps'
    name: 'step'
    folder: 'content/steps'
    create: true
    editor:
      preview: false
    fields: 
      - {label: "Step Title", name: "title", widget: "string"}
      - {label: "Step Content", name: "content", widget: "text"}
      - {label: "Step Preview", name: "preview", widget: "image"}
  - label: 'Costs'
    name: 'cost'
    folder: 'content/costs'
    create: true
    editor:
      preview: false
    fields: 
      - {label: "Product Name", name: "name", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Per Household", name: "household", widget: "boolean", required: false}
      - label: "Product Type"
        name: "type"
        widget: "select"
        options:
          - { label: "One-Time Payment", value: "onetime"}
          - { label: "Ongoing Payment", value: "ongoing"}
  - label: 'Cost Breakdowns'
    name: 'breakdown'
    folder: 'content/breakdowns'
    create: true
    editor:
      preview: false
    fields: 
      - {label: "Product Name", name: "name", widget: "string"}
      - {label: "Product Details", name: "content", widget: "markdown"}
      - label: "Product Breakdown List"
        name: "list"
        widget: "list"
        allow_add: true
        summary: "{{fields.content}}"
        field: {label: "Content", name: "content", widget: "text"}
      - label: "Product Type"
        name: "type"
        widget: "select"
        options:
          - { label: "One-Time Payment", value: "onetime"}
          - { label: "Ongoing Payment", value: "ongoing"}